skinparam {
    noteFontStyle bold
    noteFontColor #ffffff
    noteBackgroundColor #7f8c8d
    noteBorderColor #7f8c8d

    activityArrowColor #000000
    activityBackgroundColor #eeeeee
    activityBorderColor #999999
    activityStartColor #000000
    activityEndColor #000000
    activityBarColor #000000
    activityFontColor<<page>> #ffffff
    activityFontStyle<<page>> bold
    activityBorderColor<<page>> #2980b9
    activityBackgroundColor<<page>> #3498db

    activityFontColor<<error>> #ffffff
    activityFontStyle<<error>> bold
    activityBorderColor<<error>> #c0392b
    activityBackgroundColor<<error>> #e74c3c
}