@startuml

  hide footbox
  Actor User
  User -> Action: do something
  box "material-flux"
    participant Action
    participant Context
    participant Store
  end box

  Action -> Context: dispatch *event*
  Context <-- Store: receive *event*
  Store -> Store: "change" event
  Store <-- View: Observe "change" event
  View -> View: Update View

@enduml