@startuml

  hide footbox
  Actor User
  User -> View: Do something
  View -> Action: Call method
  box "material-flux"
    participant Action
    participant Context
    participant Store
  end box

  Action -> Context: Dispatch *event*
  Context <-- Store: Receive *event*
  Store -> Store: Emit "change" event
  Store <-- View: Observe "change" event
  View -> View: Update View


@enduml